# Generated by Django 5.2.6 on 2025-09-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='is_driver',
            field=models.BooleanField(default=True, help_text='Чи бере участь цей користувач у чергуванні?'),
        ),
    ]
