# Generated by Django 5.2.6 on 2025-09-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_parentprofile_is_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='color',
            field=models.CharField(default='#3788D8', help_text='Колір для відображення в календарі', max_length=7),
        ),
    ]
